site_name: Радар
site_url: https://lyolich777ka.gitlab.io/opensource-radar/
docs_dir: docs

theme:
  name: material
  language: ru
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Тёмная тема
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Светлая тема
  features:
    - navigation.instant
    - navigation.tracking
    - search.highlight

plugins:
  - search

extra_javascript:
  - https://fastly.jsdelivr.net/npm/jquery/dist/jquery.min.js
  - https://fastly.jsdelivr.net/npm/echarts/dist/echarts.min.js
  - assets/javascripts/interactive_graph.js

