#!/usr/bin/env python3
"""Generates docs/adr/ADR-INDEX.md from every docs/adr/*.md file's YAML
frontmatter (id, status, supersedes, superseded_by) plus each file's
own "# NNNN — Title" heading line.

Never hand-edit ADR-INDEX.md -- re-run this script after adding or
editing an ADR.
"""
import re
import sys
from pathlib import Path

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)
FIELD_RE = re.compile(r"^(id|status|supersedes|superseded_by):\s*(.*)$", re.MULTILINE)
TITLE_RE = re.compile(r"^#\s+\d{4}\s+—\s+(.+)$", re.MULTILINE)


def parse_adr(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")

    fm_match = FRONTMATTER_RE.match(text)
    if not fm_match:
        raise ValueError(f"{path}: no YAML frontmatter found")
    frontmatter = dict(FIELD_RE.findall(fm_match.group(1)))

    title_match = TITLE_RE.search(text)
    if not title_match:
        raise ValueError(f"{path}: no '# NNNN — Title' heading found")

    return {
        "id": frontmatter.get("id", ""),
        "title": title_match.group(1).strip(),
        "status": frontmatter.get("status", ""),
        "supersedes": frontmatter.get("supersedes", "null"),
        "superseded_by": frontmatter.get("superseded_by", "null"),
        "filename": path.name,
    }


def render_cell(value: str) -> str:
    return value if value and value != "null" else "null"


def generate_index(adr_dir: Path) -> str:
    paths = sorted(
        p for p in adr_dir.glob("*.md") if p.name != "ADR-INDEX.md"
    )
    rows = [parse_adr(p) for p in paths]

    lines = [
        "# ADR Index",
        "",
        "Generated by `scripts/generate_adr_index.py` -- never hand-edit.",
        "Derived from every `docs/adr/*.md` file's YAML frontmatter --",
        "re-run after adding or editing an ADR in this session.",
        "",
        "| ID | Title | Status | Supersedes | Superseded by |",
        "|---|---|---|---|---|",
    ]
    for row in rows:
        lines.append(
            f"| [{row['id']}]({row['filename']}) | {row['title']} | "
            f"{row['status']} | {render_cell(row['supersedes'])} | "
            f"{render_cell(row['superseded_by'])} |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    repo_root = Path(__file__).resolve().parent.parent
    adr_dir = repo_root / "docs" / "adr"

    if not adr_dir.is_dir():
        print(f"generate_adr_index: {adr_dir} not found", file=sys.stderr)
        return 2

    print(generate_index(adr_dir))
    return 0


if __name__ == "__main__":
    sys.exit(main())
